### ISSUE TITLE
Datenmodell für Journey

### ISSUE THREAD

**Issue by blackforestsolutions** [blackforestsolutions/dravelopsdatamodel#3]
- [x] Builder Pattern
- [ ] Tests für Konstruktoren
- [ ] Tests für die Helfermethoden
- [ ] DravelOpsMapper
- [ ] Tests für den DravelOpsMapper

**Comment by jobdk** [comment]
hi @hennihaus , is implemented and ready for test development

**Comment by blackforestsolutions** [comment]
Ja, kann ich machen:D

**Comment by jobdk** [comment]
richtig schön wie bei der arbeit haha
