### ISSUE TITLE
Datenmodell für TravelPoint

### ISSUE THREAD

**Issue by blackforestsolutions** [blackforestsolutions/dravelopsdatamodel#4]
- [x] Builder Pattern
- [ ] DravelOpsMapper
- [ ] Tests für Builder Pattern
- [ ] Tests für DravelOpsMapper

**Comment by jobdk** [comment]
hi @hennihaus , is implemented and ready for test development

**Comment by blackforestsolutions** [comment]
Ja, kann ich machen.
